/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IClientUpdatesInterface extends Interface {
  getFunction(
    nameOrSignature: "LIGHT_CLIENT_TYPE" | "updateClient"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "LIGHT_CLIENT_TYPE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateClient",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "LIGHT_CLIENT_TYPE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateClient",
    data: BytesLike
  ): Result;
}

export interface IClientUpdates extends BaseContract {
  connect(runner?: ContractRunner | null): IClientUpdates;
  waitForDeployment(): Promise<this>;

  interface: IClientUpdatesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LIGHT_CLIENT_TYPE: TypedContractMethod<[], [bigint], "view">;

  updateClient: TypedContractMethod<
    [proof: BytesLike, height: BigNumberish, appHash: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LIGHT_CLIENT_TYPE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateClient"
  ): TypedContractMethod<
    [proof: BytesLike, height: BigNumberish, appHash: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
