/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface VenusInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "chainId"
      | "counterParty"
      | "lastReceivedTransmission"
      | "prover"
      | "receiveEvent"
      | "receiveReceipt"
      | "receiveTransmissionEvent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "SuccessfulReceipt"
      | "TransmissionReceived"
      | "TransmitToHouston"
      | "ValidCounterpartyEvent"
  ): EventFragment;

  encodeFunctionData(functionFragment: "chainId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "counterParty",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastReceivedTransmission",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "prover", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiveEvent",
    values: [BigNumberish, BytesLike, AddressLike, BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveReceipt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveTransmissionEvent",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "chainId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "counterParty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastReceivedTransmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "prover", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveTransmissionEvent",
    data: BytesLike
  ): Result;
}

export namespace SuccessfulReceiptEvent {
  export type InputTuple = [srcChainId: BytesLike, receiptRLP: BytesLike];
  export type OutputTuple = [srcChainId: string, receiptRLP: string];
  export interface OutputObject {
    srcChainId: string;
    receiptRLP: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransmissionReceivedEvent {
  export type InputTuple = [message: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [message: string, timestamp: bigint];
  export interface OutputObject {
    message: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransmitToHoustonEvent {
  export type InputTuple = [message: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [message: string, timestamp: bigint];
  export interface OutputObject {
    message: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidCounterpartyEventEvent {
  export type InputTuple = [
    counterParty: AddressLike,
    topics: BytesLike[],
    unindexed: BytesLike
  ];
  export type OutputTuple = [
    counterParty: string,
    topics: string[],
    unindexed: string
  ];
  export interface OutputObject {
    counterParty: string;
    topics: string[];
    unindexed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Venus extends BaseContract {
  connect(runner?: ContractRunner | null): Venus;
  waitForDeployment(): Promise<this>;

  interface: VenusInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  chainId: TypedContractMethod<[], [string], "view">;

  counterParty: TypedContractMethod<[], [string], "view">;

  lastReceivedTransmission: TypedContractMethod<[], [string], "view">;

  prover: TypedContractMethod<[], [string], "view">;

  receiveEvent: TypedContractMethod<
    [
      logIndex: BigNumberish,
      proof: BytesLike,
      expectedEmitter: AddressLike,
      expectedTopics: BytesLike[],
      expectedUnindexedData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  receiveReceipt: TypedContractMethod<[proof: BytesLike], [void], "nonpayable">;

  receiveTransmissionEvent: TypedContractMethod<
    [logIndex: BigNumberish, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "chainId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "counterParty"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastReceivedTransmission"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "prover"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiveEvent"
  ): TypedContractMethod<
    [
      logIndex: BigNumberish,
      proof: BytesLike,
      expectedEmitter: AddressLike,
      expectedTopics: BytesLike[],
      expectedUnindexedData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "receiveReceipt"
  ): TypedContractMethod<[proof: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "receiveTransmissionEvent"
  ): TypedContractMethod<
    [logIndex: BigNumberish, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "SuccessfulReceipt"
  ): TypedContractEvent<
    SuccessfulReceiptEvent.InputTuple,
    SuccessfulReceiptEvent.OutputTuple,
    SuccessfulReceiptEvent.OutputObject
  >;
  getEvent(
    key: "TransmissionReceived"
  ): TypedContractEvent<
    TransmissionReceivedEvent.InputTuple,
    TransmissionReceivedEvent.OutputTuple,
    TransmissionReceivedEvent.OutputObject
  >;
  getEvent(
    key: "TransmitToHouston"
  ): TypedContractEvent<
    TransmitToHoustonEvent.InputTuple,
    TransmitToHoustonEvent.OutputTuple,
    TransmitToHoustonEvent.OutputObject
  >;
  getEvent(
    key: "ValidCounterpartyEvent"
  ): TypedContractEvent<
    ValidCounterpartyEventEvent.InputTuple,
    ValidCounterpartyEventEvent.OutputTuple,
    ValidCounterpartyEventEvent.OutputObject
  >;

  filters: {
    "SuccessfulReceipt(bytes32,bytes)": TypedContractEvent<
      SuccessfulReceiptEvent.InputTuple,
      SuccessfulReceiptEvent.OutputTuple,
      SuccessfulReceiptEvent.OutputObject
    >;
    SuccessfulReceipt: TypedContractEvent<
      SuccessfulReceiptEvent.InputTuple,
      SuccessfulReceiptEvent.OutputTuple,
      SuccessfulReceiptEvent.OutputObject
    >;

    "TransmissionReceived(bytes32,uint64)": TypedContractEvent<
      TransmissionReceivedEvent.InputTuple,
      TransmissionReceivedEvent.OutputTuple,
      TransmissionReceivedEvent.OutputObject
    >;
    TransmissionReceived: TypedContractEvent<
      TransmissionReceivedEvent.InputTuple,
      TransmissionReceivedEvent.OutputTuple,
      TransmissionReceivedEvent.OutputObject
    >;

    "TransmitToHouston(bytes32,uint64)": TypedContractEvent<
      TransmitToHoustonEvent.InputTuple,
      TransmitToHoustonEvent.OutputTuple,
      TransmitToHoustonEvent.OutputObject
    >;
    TransmitToHouston: TypedContractEvent<
      TransmitToHoustonEvent.InputTuple,
      TransmitToHoustonEvent.OutputTuple,
      TransmitToHoustonEvent.OutputObject
    >;

    "ValidCounterpartyEvent(address,bytes[],bytes)": TypedContractEvent<
      ValidCounterpartyEventEvent.InputTuple,
      ValidCounterpartyEventEvent.OutputTuple,
      ValidCounterpartyEventEvent.OutputObject
    >;
    ValidCounterpartyEvent: TypedContractEvent<
      ValidCounterpartyEventEvent.InputTuple,
      ValidCounterpartyEventEvent.OutputTuple,
      ValidCounterpartyEventEvent.OutputObject
    >;
  };
}
