/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IbcEventsEmitter,
  IbcEventsEmitterInterface,
} from "../../IbcDispatcher.sol/IbcEventsEmitter";

const _abi = [
  {
    type: "event",
    name: "Acknowledgement",
    inputs: [
      {
        name: "sourcePortAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "sourceChannelId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "sequence",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AcknowledgementError",
    inputs: [
      {
        name: "receiver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "error",
        type: "bytes",
        indexed: false,
        internalType: "bytes",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChannelCloseConfirm",
    inputs: [
      {
        name: "portAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "channelId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChannelCloseConfirmError",
    inputs: [
      {
        name: "receiver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "error",
        type: "bytes",
        indexed: false,
        internalType: "bytes",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChannelCloseInit",
    inputs: [
      {
        name: "portAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "channelId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChannelCloseInitError",
    inputs: [
      {
        name: "receiver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "error",
        type: "bytes",
        indexed: false,
        internalType: "bytes",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChannelOpenAck",
    inputs: [
      {
        name: "receiver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "channelId",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChannelOpenAckError",
    inputs: [
      {
        name: "receiver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "error",
        type: "bytes",
        indexed: false,
        internalType: "bytes",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChannelOpenConfirm",
    inputs: [
      {
        name: "receiver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "channelId",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChannelOpenConfirmError",
    inputs: [
      {
        name: "receiver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "error",
        type: "bytes",
        indexed: false,
        internalType: "bytes",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChannelOpenInit",
    inputs: [
      {
        name: "receiver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "version",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "ordering",
        type: "uint8",
        indexed: false,
        internalType: "enum ChannelOrder",
      },
      {
        name: "feeEnabled",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "connectionHops",
        type: "string[]",
        indexed: false,
        internalType: "string[]",
      },
      {
        name: "counterpartyPortId",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChannelOpenInitError",
    inputs: [
      {
        name: "receiver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "error",
        type: "bytes",
        indexed: false,
        internalType: "bytes",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChannelOpenTry",
    inputs: [
      {
        name: "receiver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "version",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "ordering",
        type: "uint8",
        indexed: false,
        internalType: "enum ChannelOrder",
      },
      {
        name: "feeEnabled",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "connectionHops",
        type: "string[]",
        indexed: false,
        internalType: "string[]",
      },
      {
        name: "counterpartyPortId",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "counterpartyChannelId",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ChannelOpenTryError",
    inputs: [
      {
        name: "receiver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "error",
        type: "bytes",
        indexed: false,
        internalType: "bytes",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RecvPacket",
    inputs: [
      {
        name: "destPortAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "destChannelId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "sequence",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SendPacket",
    inputs: [
      {
        name: "sourcePortAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "sourceChannelId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "packet",
        type: "bytes",
        indexed: false,
        internalType: "bytes",
      },
      {
        name: "sequence",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
      {
        name: "timeoutTimestamp",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Timeout",
    inputs: [
      {
        name: "sourcePortAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "sourceChannelId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "sequence",
        type: "uint64",
        indexed: true,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TimeoutError",
    inputs: [
      {
        name: "receiver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "error",
        type: "bytes",
        indexed: false,
        internalType: "bytes",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WriteAckPacket",
    inputs: [
      {
        name: "writerPortAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "writerChannelId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "sequence",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
      {
        name: "ackPacket",
        type: "tuple",
        indexed: false,
        internalType: "struct AckPacket",
        components: [
          {
            name: "success",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "data",
            type: "bytes",
            internalType: "bytes",
          },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WriteTimeoutPacket",
    inputs: [
      {
        name: "writerPortAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "writerChannelId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "sequence",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
      {
        name: "timeoutHeight",
        type: "tuple",
        indexed: false,
        internalType: "struct Height",
        components: [
          {
            name: "revision_number",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "revision_height",
            type: "uint64",
            internalType: "uint64",
          },
        ],
      },
      {
        name: "timeoutTimestamp",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
] as const;

export class IbcEventsEmitter__factory {
  static readonly abi = _abi;
  static createInterface(): IbcEventsEmitterInterface {
    return new Interface(_abi) as IbcEventsEmitterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IbcEventsEmitter {
    return new Contract(address, _abi, runner) as unknown as IbcEventsEmitter;
  }
}
