name: Validate Bindings

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  verify-bindings:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.3"

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1.2.0

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Install ABIGen
        run: |
          go install github.com/ethereum/go-ethereum/cmd/abigen@v1.13.5

      - name: Generate Bindings
        run: |
          bun install --frozen-lockfile
          bun run build

      - name: Check for Bindings Changes
        run: |
          changes=$( git status --porcelain -- ./bindings ./src/evm/contracts )
          if [ -n "$changes" ]; then
            echo -e "Changes in Generated Bindings:\n$changes"
            exit 1
          fi
      - name: Upload ts bindings artifact on error
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: ts-bindings 
          path: ./src/evm/contracts/
      - name: Upload go bindings artifact on error
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: go-bindings 
          path: ./bindings/
